### ISSUE TITLE
Provide DbVisualizer Syntax

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/virtual-schemas#233]
For all the dialects on this page, you need to add a 
`--/`
in front of the `Create or replace script ...` so that they work in DbVisualizer. As this doesn't hurt in other Sql-Clients I propose to add them so that our customers can easily get started when using DbVisualizer.

https://github.com/exasol/virtual-schemas/tree/master/doc/dialects

**Comment by redcatbear** [comment]
I had that discussion in other context. I don't think we should start modifying SQL statements for a single client. 
1. This must be fixed in DbVisualizer
1. It is confusing to all users who don't use DbVisualizer
1. There is no guarantee that this does not interfere with other clients
The correct approach is to ask the maker of DbVisualizer to improve compatibility. I am aware that this is a Exasol SQL dialect thing, but multi-database clients need to implement dialects anyway.
